# https://github.com/helix-editor/helix/pull/14356
# [theme]
# dark = "gruvbox_dark_hard"
# light = "gruvbox_light_hard"
theme = "gruvbox_dark_hard"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "‚ñè"

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 400

[editor]
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"
