# This file will be merged with this: https://github.com/helix-editor/helix/blob/master/languages.toml
# A key for which the value is an inline table or an array will not be merged, but overwirtten.
# So the default configuration for that key is lost. 

# Web development config slop from here: https://dev.to/morlinbrot/configure-helix-for-typescript-eslint-prettierdprint-33bk

# TODO: add spell check to .git/COMMIT_EDITMSG

[language-server]
harper = { command = "harper-ls", args = ["--stdio"] }
rumdl = { command = "rumdl", args = ["server"] }
emmet = { command = "emmet-language-server", args = ["--stdio"] }

[language-server.eslint]
command = "eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = true }
format = { enable = true }
nodePath = ""
quiet = false
rulesCustomizations = []
run = "onType"
validate = "on"
experimental = {}
problems = { shortenToSingleLine = false }

[language-server.eslint.config.codeAction]
disableRuleComment = { enable = true, location = "separateLine" }
showDocumentation = { enable = false }

[language-server.vscode-json-language-server.config]
json = { validate = { enable = true }, format = { enable = true } }
provideFormatter = true

[language-server.vscode-css-language-server.config]
css = { validate = { enable = true } }
scss = { validate = { enable = true } }
less = { validate = { enable = true } }
provideFormatter = true

[[language]]
name = "git-commit"
language-servers = ["harper"]

[[language]]
name = "markdown"
soft-wrap = { enable = true, wrap-at-text-width = true }
language-servers = ["marksman", "rumdl", "harper"]

[[language]]
name = "typst"
soft-wrap = { enable = true, wrap-at-text-width = true }
language-servers = ["tinymist", "harper"]

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format"] }

[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "eslint", "emmet"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "eslint", "emmet"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "javascript"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = "dprint", args = ["fmt", "--stdin", "json"] }
auto-format = true

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "superhtml", "emmet"]
auto-format = true

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "emmet"]
auto-format = true
